### ISSUE TITLE
feature request: add bench.press() constructor function

### ISSUE THREAD

**Issue by spytheman** [mvlootman/vbench#1]
This will allow users to write code like this:
```
mut training := bench.press({
                warmup_secs: 2
                bench_secs: 5
                repetitions: 4
})
```

**Comment by mvlootman** [comment]
I like the gym analogy (bench / press / repetitions) :-)
Adding the constructor function is a good idea.
The number of repetitions are now being estimated by sampling the calling code for ~100ms, this is done to determine a more accurate benchmark.

Specifying the number of repetitions up front would then just call the code to be benchmarked n-times. Instead of sampling the code and then run it for n-seconds.

**Comment by mvlootman** [comment]
Added the constructor function (so defaults are in place)
```
 mut b := bench.new(bench.Benchmark{
                warmup_secs: 2,
                bench_secs: 5
        })
```

I am still not sure if specifying the number or repetitions directly is a good idea because it might give inaccurate/skewed results. Instead the user can lengthen or shorten the time the benchmark should run.
